### ISSUE TITLE
Params are loaded as strings

### ISSUE THREAD

**Issue by sirykd** [aimhubio/aimlflow#6]
It seems that hyperparameters imported from MLflow are treated as strings in Aim.
It first occurred in my experiments, so I tried the `tune.py` example from this repo to double-check:

<img width="753" alt="Screenshot 2023-01-30 at 18 32 12" src="https://user-images.githubusercontent.com/23129117/215550956-15c9b979-9a30-406b-81a7-fb096c24a171.png">

It obviously affects queries and hyperparameters plots, especially when some floats are expressed in scientific notation, so even the ordering becomes broken.

The same runs are parsed correctly in MLflow UI.
Also, there is no such issue with metrics, as they are being loaded as intended.

Package versions are as follows:
```
aim-mlflow              0.1.1
mlflow                  2.1.1
```

Could there be anything on my side I'm doing wrong, or do you have any idea how it can be fixed?

**Comment by mihran113** [comment]
Hey @sirykd! Thanks for the report. I don't think that there's anything wrong on your side, I'll have a look at this, should be relatively easy to fix.

**Comment by mihran113** [comment]
@sirykd I've done some digging and seems the params in mlflow are saved as strings actually, cause when accessing them via SDK, this is what it looks like: 
```
print(run.data.params)
{'l2': '64', 'batch_size': '2', 'lr': '0.0037286350327671598', 'l1': '16'}
```

Will check what can be done here.

**Comment by sirykd** [comment]
@mihran113 At least it seems to be consistent with their docs:

|  |  |
|-|-|
|<img width="408" alt="Screenshot 2023-01-31 at 20 06 38" src="https://user-images.githubusercontent.com/23129117/215883058-e992802c-dbd0-4a6a-a164-5903db37085f.png"> | <img width="998" alt="Screenshot 2023-01-31 at 20 07 24" src="https://user-images.githubusercontent.com/23129117/215883084-658a4c32-ecdb-4d9c-aa11-1ca94e77f8a4.png"> |

Out of curiosity, I tried to find any place where some kind of cast back into numerics happens but didn't succeed.

**Comment by mihran113** [comment]
They do it on UI side apparently, cause when looking into responses in browser, the params are still represented as strings there
<img width="1788" alt="Screenshot 2023-02-01 at 01 27 53" src="https://user-images.githubusercontent.com/6143646/215887367-f255fb6f-34dd-482a-8639-736d301ebeaa.png">

**Comment by sirykd** [comment]
So I had another look, searching specifically for their "Parallel Coordinates Plot" because it handles both numbers and strings, and I guess I've found something:

https://github.com/mlflow/mlflow/blob/e43a9b774ebb80f0577a72c1f89a63edf02a0d3a/mlflow/server/js/src/experiment-tracking/components/ParallelCoordinatesPlotView.js#L162-L214

**Comment by sirykd** [comment]
So, I temporarily ended up using the following code as a hotfix:

```python
import collections
from ast import literal_eval


def map_nested_dicts(ob, func):
    if isinstance(ob, collections.Mapping):
        return {k: map_nested_dicts(v, func) for k, v in ob.items()}
    else:
        return func(ob)


def parse_string(s):
    assert isinstance(s, str), f"Expected string, got: {type(s)}"
    try:
        return literal_eval(s.strip())
    except:  # noqa: E722
        return s


def collect_run_params(aim_run, mlflow_run):
    # ...
    aim_run["params"] = map_nested_dicts(mlflow_run.data.params, parse_string)
    # ...
```

**Comment by mihran113** [comment]
Yeah, that should do the trick I guess, if mlflow guarantees that all the values are strings.
Can I ask you to open a PR with this changes?

**Comment by sirykd** [comment]
> Yeah, that should do the trick I guess, if mlflow guarantees that all the values are strings.

I don't know about the guarantees, but the `assert` can be replaced with a type-check, I guess.

> Can I ask you to open a PR with this changes?

Sure :) I'll prepare it soon.
